#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
#this is your scriptpath
# echo $SCRIPTPATH

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

########## This script makes the colors of your polybar and terminals#########
sh $SCRIPTPATH/scripts/wal.sh
##############################################################################

#change your keyboard if you need it - azerty or qwerty
#setxkbmap -layout be
keybLayout=$(setxkbmap -v | awk -F "+" '/symbols/ {print $2}')

if [ $keybLayout = "be" ]; then
  cp ~/.config/leftwm/config-azerty.ron ~/.config/leftwm/config.ron
fi

#keep toml until wal project makes the file
#leftwm command "LoadTheme $SCRIPTPATH/theme.ron"
leftwm command "LoadTheme $SCRIPTPATH/theme.toml"

function run {
  if ! pgrep -x $(basename $1 | head -c 15) 1>/dev/null;
  then
    $@&
  fi
}

# diversity of apps to start
fastcompmgr &
nm-applet &
pamac-tray &
xfce4-power-manager &
numlockx on &
blueberry-tray &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
volumeicon &
run xfce4-clipman

#caffeine &
#vivaldi-stable &
#firefox &
#thunar &
#dropbox &
#insync start &
#discord &
#spotify &

#mainbar
index=0
monitors=($(polybar -m | sed s/:.*//))
leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  barname="mainbar$index"
  monitor=${monitors[index]} width=$(( width - 16 )) polybar -c "$SCRIPTPATH"/polybar/polybartop.config $barname &> /dev/null &
  monitor=${monitors[index]} width=$(( width - 16 )) polybar -c "$SCRIPTPATH"/polybar/polybarbottom.config $barname &> /dev/null &
  let index=index+1
done
